apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJVMnhoZG05dGFYSkVaWFk2WjJod1gwMXpiRzk0VkdGSVFrazJSVXRrVVhoNFNWbFpVR05tUWpnME9HMXBiVEp1YjBsb01nPT0iCgkJfQoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
